<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Reset_password extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Reset_password_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','reset_password/list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Reset_password_model->json();
    }

    public function person($id) {
        header('Content-Type: application/json');
        $data['identitas'] = $this->Reset_password_model->person($id)->row();
        echo json_encode($data);
    }
    public function update()
    {
        header('Content-Type: application/json');
        $data['update'] = $this->Reset_password_model->update();
        echo json_encode($data);
    }

}

/* End of file Informasi.php */
/* Location: ./application/controllers/Informasi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-02-21 21:38:12 */
/* http://harviacode.com */